worlds:
    world:
      1:
        world: world
        x: 0
        y: 64
        z: 0
        yaw: 0
        pitch: 0
      2:
        world: world
        x: 0
        y: 64
        z: 0
        yaw: 0
        pitch: 0
    hungergame:
      1:
        world: hungergame
        x: 0
        y: 64
        z: 0
        yaw: 0
        pitch: 0
      2:
        world: hungergame
        x: 0
        y: 64
        z: 0
        yaw: 0
        pitch: 0

chest: